# ══════════════════════════════════════════════════════════════════
# lib/config.sh — Конфигурация: safe-loader, save, validate, update
# ══════════════════════════════════════════════════════════════════

# Whitelist допустимых ключей конфига
readonly CONFIG_KEYS="SERVER_IP|PROXY_PORT|FAKETLS_DOMAIN|EXTERNAL_FALLBACK|SECRET|CONTAINER_NAME|MTG_IMAGE|SNI_MODE|MTG_INTERNAL_PORT|STREAM_CONF|ENGINE"

# ── Проверка наличия конфига ──
config_exists() {
    [[ -f "$CONFIG_FILE" ]]
}

# ── Безопасная загрузка конфига (без source) ──
load_config_safe() {
    [[ -f "$CONFIG_FILE" ]] || return 1

    while IFS='=' read -r k v; do
        # Убираем возможные пробелы и кавычки
        v="${v%\"}"
        v="${v#\"}"
        v="${v%\'}"
        v="${v#\'}"

        case "$k" in
            SERVER_IP)          SERVER_IP="$v" ;;
            PROXY_PORT)         PROXY_PORT="$v" ;;
            FAKETLS_DOMAIN)     FAKETLS_DOMAIN="$v" ;;
            SECRET)             SECRET="$v" ;;
            SNI_MODE)           SNI_MODE="$v" ;;
            ENGINE)             PROXY_ENGINE="$v" ;;
            # Остальные ключи — в переменные, но не перезаписываем readonly
        esac
    done < <(grep -E "^(${CONFIG_KEYS})=" "$CONFIG_FILE" 2>/dev/null)
}

# ── Валидация загруженного конфига ──
validate_loaded_config() {
    local valid=true

    if [[ -z "${SERVER_IP:-}" ]]; then
        log_warn "Конфиг: SERVER_IP пуст"
        valid=false
    fi

    if [[ -z "${SECRET:-}" ]]; then
        log_warn "Конфиг: SECRET пуст"
        valid=false
    fi

    if [[ -z "${FAKETLS_DOMAIN:-}" ]]; then
        log_warn "Конфиг: FAKETLS_DOMAIN пуст"
        valid=false
    fi

    [[ "$valid" == true ]]
}

# ── Сохранение конфига ──
save_config() {
    cat > "$CONFIG_FILE" << EOF
# MTProto Proxy Config — created $(date '+%Y-%m-%d %H:%M:%S')
SERVER_IP=${SERVER_IP}
PROXY_PORT=${PROXY_PORT}
FAKETLS_DOMAIN=${FAKETLS_DOMAIN}
EXTERNAL_FALLBACK=${EXTERNAL_FALLBACK}
SECRET=${SECRET}
CONTAINER_NAME=${CONTAINER_NAME}
MTG_IMAGE=${MTG_IMAGE}
SNI_MODE=${SNI_MODE}
MTG_INTERNAL_PORT=${MTG_INTERNAL_PORT}
STREAM_CONF=${STREAM_CONF}
ENGINE=${PROXY_ENGINE}
EOF
    chmod 600 "$CONFIG_FILE"
    log_ok "Конфигурация сохранена в ${BOLD}${CONFIG_FILE}${RESET}"
}

# ── Обновление одного ключа в конфиге ──
update_config_key() {
    local key="$1"
    local value="$2"

    if [[ ! -f "$CONFIG_FILE" ]]; then
        log_err "Конфиг не найден: $CONFIG_FILE"
        return 1
    fi

    if grep -q "^${key}=" "$CONFIG_FILE"; then
        sed -i "s/^${key}=.*/${key}=${value}/" "$CONFIG_FILE"
    else
        echo "${key}=${value}" >> "$CONFIG_FILE"
    fi
}

# ── Выбор FakeTLS домена ──
select_faketls_domain() {
    # Если уже задан (через конфиг при обновлении) — не трогаем
    if [[ -n "${FAKETLS_DOMAIN}" ]]; then
        return 0
    fi

    # Всегда берём RF-домен: в SNI-режиме домен сайта вызовет конфликт в nginx map,
    # а в direct-режиме у пользователя нет своих доменов на сервере.
    FAKETLS_DOMAIN="${RF_DOMAINS[$RANDOM % ${#RF_DOMAINS[@]}]}"
    log_ok "FakeTLS домен: ${BOLD}${FAKETLS_DOMAIN}${RESET} (рандом из RF-списка)"
}

# ══════════════════════════════════════════════════════════════════
# Telemt-специфичные функции конфигурации
# ══════════════════════════════════════════════════════════════════

# ── Конвертация ee-секрета mtg в 32-hex для Telemt ──
# mtg secret: ee + hex(domain) + 32_hex_random → нужно извлечь 32 hex-символа
# Если секрет уже 32 hex — возвращаем как есть
convert_mtg_secret_to_telemt() {
    local mtg_secret="$1"

    # Если секрет уже в формате 32-hex (Telemt native) — возвращаем
    if [[ ${#mtg_secret} -eq 32 ]] && [[ "$mtg_secret" =~ ^[0-9a-fA-F]{32}$ ]]; then
        echo "$mtg_secret"
        return 0
    fi

    # mtg ee-secret: первые 2 символа 'ee', потом hex(domain), потом 32 символа секрета
    # Нам нужны первые 32 hex-символа после 'ee' префикса
    # Но проще сгенерировать новый чистый 32-hex
    # При миграции генерируем новый секрет — это необходимо, т.к. формат несовместим
    local new_secret
    new_secret=$(openssl rand -hex 16)
    echo "$new_secret"
}

# ── Генерация config.toml для Telemt ──
generate_telemt_config() {
    log_step "${ICON_GEAR} Генерация конфигурации Telemt"

    mkdir -p "${TELEMT_CONFIG_DIR}"

    # Определяем порт для listener
    local listen_port=443
    if [[ "$SNI_MODE" == true ]]; then
        listen_port=${MTG_INTERNAL_PORT}
    fi

    cat > "${TELEMT_CONFIG_FILE}" << TOMLEOF
### Telemt Config — generated by deploy_mt.sh $(date '+%Y-%m-%d %H:%M:%S')
log_level = "normal"

[server.api]
enabled = false

[[server.listeners]]
ip = "0.0.0.0"
port = ${listen_port}

[censorship]
tls_domain = "${FAKETLS_DOMAIN}"
mask = true
tls_emulation = true
tls_front_dir = "/app/tlsfront"

[performance]
download_buffer_size = 131072
me_pool_size = 8
workers = 2

[access.users]
admin = "${SECRET}"
TOMLEOF

    chmod 644 "${TELEMT_CONFIG_FILE}"
    log_ok "Конфиг Telemt создан: ${BOLD}${TELEMT_CONFIG_FILE}${RESET}"
    log_sub "TLS-домен: ${FAKETLS_DOMAIN}"
    log_sub "Маскировка (TCP Splicing): включена"
    log_sub "TLS-эмуляция: включена"
}
